# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_auto_20171127_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lnrz_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.LnrzUrl')),
            ],
        ),
    ]
